# Generated by Django 2.1.5 on 2019-02-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20190213_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
