# Generated by Django 2.1.5 on 2019-02-24 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190223_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2019, 2, 24, 7, 27, 7, 946272, tzinfo=utc)),
        ),
    ]
