# Generated by Django 2.1.5 on 2019-02-25 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190224_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2019, 2, 25, 20, 36, 26, 139511, tzinfo=utc)),
        ),
    ]
