# Generated by Django 2.1.5 on 2019-02-25 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190225_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2019, 2, 25, 21, 42, 57, 211691, tzinfo=utc)),
        ),
    ]
