# Generated by Django 2.1.5 on 2019-02-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190225_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/no-photo.png', null=True, upload_to='profile_pics'),
        ),
    ]
